Module2 task1
htmlacademy-adaptive/2280491-cat-energy-28 pull request #2
Opened 2023-04-02 14:08 UTC by dornp

2023-04-02 16:42 UTC, wrgraff requested changes
Вообще, критичных ошибок и правда мало.
Немного хочется подтянуть семантику, но это не совсем задача второго уровня верстки, тут у нас о другом речь. Тем не менее, эти моменты я отметил.

Еще даю ссылку на [правила, по которым делаю ревью](https://telegra.ph/Pravila-revyu-04-02), чтобы было проще ориентироваться

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <img class="logo-title" src="img/logo-title.svg" width="101" height="18" alt="Cat energy title">
А почему только у одной картинки класс?

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <img class="logo-title" src="img/logo-title.svg" width="101" height="18" alt="Cat energy title">
Вообще, было бы логично одну из картинок скрыть для скринридера через `aria-hidden="true"`, потому что две картинки у нас из технических соображений больше, а по факту для незрячих идею того, что тут у нас лого Кэт Энерджи можно передать и в одной картинке

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <button class="main-nav__toggle main-nav__toggle--active" type="button">
Пока не очень понял, зачем модификатор `main-nav__toggle--active`

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +              <a href="form.html">Подбор программы</a>
Можно и ссылкам дать классы, мы же точно будем их стилизовать

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +      <div class="hero">
А почему этот блок не подходит для разметки через `<section>`?
У него вполне себе отдельный законченный смысл

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <h1 class="main-title">Функциональное питание для котов</h1>
Тут вроде бы все элементы блока `hero`, а заголовок почему-то нет. Стоит и его сделать элементом, пожалуй

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <img class="hero__image" src="img/can-hero.png" width="280" height="270" alt="product">
`alt` это все-таки описание, не очень паравильно писать там просто `product`

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +      <div class="program-wrapper">
Тут тоже хочется `<section>` использовать. Вполне состоятельный блок тоже

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <section class="program">
Все-таки обычно делается несколько иначе логика разметки. Чтобы не создавать ради обертки еще один БЭМ-блок, блоком делают самую внешнюю обертку:
```html
<section class="program">
  <h2> ... </h2>
  <section class="program__item">
    ...
  </section>
  <section class="program__item">
    ...
  </section>
</section>
```

Иногда требуется создать обертку, чтобы центрировать содержимое блока. Ее можно создать внутри:
```html
<section class="program">
  <div class="program__container">
    <h2> ... </h2>
    <section class="program__item">
      ...
    </section>
    <section class="program__item">
      ...
    </section>
  </div>
</section>
```

_P.S.: Для единообразия можно обертки добавить в каждую основную секцию страницы, даже если изначально можно центрировать и сам блок_

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +            <p >
Тут что-то поломалось, видимо случайно

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +          <li class="about-item">
А есть ли большой смысл создавать отдельный БЭМ-блок для элемента списка?

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +            <p class="about-item__text">
Параграфы в принципе нет необходимости создавать внутри элементов списка

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <h2 class="secondary-title">Живой пример</h2>
Пока это не проблема, всегда можно добавить будет, но наверняка будет удобно `secondary-title` миксовать с классом родительского блока:
```suggestion
        <h2 class="secondary-title example__title">Живой пример</h2>
```

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        </div>
Здесь можно было бы применить и более семантическую разметку. Хотя бы использовать пару параграфов, но еще лучше использовать список определений (это который `<dl>`)

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <div class="address address--size-small">
А зачем нужен тут модификатор `address--size-small`?

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +        <img class="address-map__map-image" src="img/location.png" width="320" height="362" alt="Наше местоположение">
Какой-то странный класс, почему бы не написать `address-map__image` =)

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +      <img class="logo-title" src="img/logo-title.svg" width="101" height="18" alt="Cat energy title">
Логотип тут тоже внутри ссылки будет

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +      <div class="footer__social social">
Непонятно зачем списку обертка дивом, список же сам по себе обертка для элементов списка

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +              <span class="visually-hidden">youtube</span>
Вообще, если текст скрыт, его все равно надо писать так, как он был бы написан будучи видимым:
YouTube, Telegram, В контакте

2023-04-02 16:42 UTC, wrgraff commented on source/index.html
> +      </div>
Тоже не факт, что обертка понадобится

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +            <li class="main-nav__item main-nav__item--current">
Ну, как и говорил, надо на внутренних страницах выделить правильную ссылку. Это же не главная =)

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +        <li class="product-card">
Где-то должна быть ссылка на страницу продукта

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +          <span class="product-card__title">Cat Energy PRO 500 г</span>
Ох, ну тут как минимум параграф, а не `<span>`. А можно даже и заголовок поставить, чтобы в древе доступности появился список товаров.

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +          <button class="primary-button product-card__button" type="button">Заказать</button>
На самом деле, на практике кнопки типа "Заказать" делают ссылками.

Потому что это для интернет-магазина критическая функциональность, и нужно подстраховаться и сделать так, чтобы кнопка работала без js.

Прямо в адрес ссылки может быть включен запрос с добавлением товара в корзину. При переходе на этот адрес товар добавляется в корзину и потом срабатывает переадресация обратно, где грузится страница с уже обновленной корзиной. Будет работать с перезагрузкой страницы, но зато будет работать всегда: ссылку в html-коде сломать крайне сложно.

А потом уже поверх пишется js, который останавливает переход по ссылке, сам вместо него делает запрос, получает ответ, а затем обновляет состояние корзины.

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +          <span>На самом деле вкусов гораздо больше!</span>
Очень много спанов.
Вообще, лучше фразы оборачивать в параграфы, потому что в верстке тег `<p>` это не такой параграф, который воспринимается как абзац текста, но и в принципе любой осмысленный текст. Он может состоять и из пары-тройки и слов, и содержать внутри себя элементы форм, и многое другое. Так что пользоваться ими можно смелее.

Кроме того, не стоит забывать и о других фразовых тегах, например `<strong>` и `<em>` — они не только выделяют текст визуально, но и свидетельствуют о его значимости.

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +      <div class="extra-product-catalog">
Если можно озаглавить, то почти наверняка это `<section>`, а не просто `<div>`. Вот тут даже заголовок второго уровня есть, поэтому и `<section>` просится

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +            <span class="extra-product-card__title">Сахарозаменитель</span>
Тоже, хочется сильно повысить значимость этого элемента, вплоть до заголовка

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +            </table>
Таблица из двух ячеек и одной строки — как-то перебор.
Кстати, вот интересный вариант с разметкой семантичной через список определений + размечено что именно указывается:

```html
<dl class="card-row__list">
  <dt class="visually-hidden">Объем</dt>
  <dd class="card-row__definition">1 упаковка (100 г)</dd>

  <dt class="visually-hidden">Цена</dt>
  <dd class="card-row__definition">200 р.</dd>
</dl>
```

2023-04-02 16:42 UTC, wrgraff commented on source/catalog.html
> +        </div>
Опять же, хочется поменьше элементов и посемантичнее:

```suggestion
        <p class="present">
          Закажите все и получите чехол для кота в подарок!
        </p>
```

2023-04-02 16:42 UTC, wrgraff commented on source/form.html
> +      <p class="call-to-action-phrase">
Какой огромный класс )
Кроме того, он довольно сильно привязан к смыслу фразы самой. Можно и абстрактнее и покороче, например `subheader`

2023-04-02 16:42 UTC, wrgraff commented on source/form.html
> +          </div>
`personal-data-item` и `owner-data-item` не сильно отличаются друг от друга, это мог бы быть один и тот же БЭМ-блок с разными модификаторами.

Я делал [небольшой ролик с разметкой формы](https://youtube.com/playlist?list=PL6xpnt2woRKk0btmfzM2oR6-ste7wZUWm), там есть про это часть (видео короткие)

2023-04-02 16:42 UTC, wrgraff commented on source/form.html
> +                <span class="program-item__control-mark"></span>
В принципе, можно все оформить только с использованием псевдоэлементов

2023-04-02 16:42 UTC, wrgraff commented on source/form.html
> +                  name="набор массы" value="2">
Атрибут `name` должен быть латиницей указан и совпадать у всех инпутов с `type="radio"`.
Выбор таких инпутов переключается между вариантами с одинаковым `name`. Сейчас получилась ситуация, при которой выбираться будет каждый инпут отдельно и отменить этот выбор будет нельзя.

Значение же выбранное передается через атрибут `value`.

2023-04-02 16:42 UTC, wrgraff commented on source/form.html
> +          <div>
А куда класс пропал

2023-04-02 16:42 UTC, wrgraff commented on source/form.html
> +        </p>
Будет сложновато разметить этот текст рядом с кнопкой, учитывая что они в разные элементы вложены.
Кроме того, кнопка то не относится к `fieldset`'у, она ко всей форме относится. И их логично расположить внизу как раз вместе

2023-04-03 09:01 UTC, dornp commented on source/index.html
> +        <img class="logo-title" src="img/logo-title.svg" width="101" height="18" alt="Cat energy title">
👍

2023-04-03 09:01 UTC, dornp commented on source/index.html
> +        <img class="logo-title" src="img/logo-title.svg" width="101" height="18" alt="Cat energy title">
👍

2023-04-03 09:07 UTC, dornp commented on source/index.html
> +        <button class="main-nav__toggle main-nav__toggle--active" type="button">
Я думала, active будет отвечать за открытость/закрытость меню... Что-то пошло не так. Я пока уберу.

2023-04-03 09:08 UTC, dornp commented on source/index.html
> +              <a href="form.html">Подбор программы</a>
👍

2023-04-03 09:12 UTC, dornp commented on source/index.html
> +        <img class="hero__image" src="img/can-hero.png" width="280" height="270" alt="product">
👍

2023-04-03 09:26 UTC, dornp commented on source/index.html
> +      <div class="program-wrapper">
👍

2023-04-03 09:26 UTC, dornp commented on source/index.html
> +        <h1 class="main-title">Функциональное питание для котов</h1>
👍

2023-04-03 09:26 UTC, dornp commented on source/index.html
> +      <div class="hero">
👍

2023-04-03 09:28 UTC, dornp commented on source/index.html
> +            <p >
👍

2023-04-03 09:40 UTC, dornp commented on source/index.html
> +        <section class="program">
Я хочу уточнить по поводу обёртки, я не совсем понимаю, зачем сейчас нужна ещё одна обёртка, если блок и так можно центрировать...

2023-04-03 09:45 UTC, dornp commented on source/index.html
> +          <li class="about-item">
👍

2023-04-03 09:45 UTC, dornp commented on source/index.html
> +            <p class="about-item__text">
👍

2023-04-03 10:13 UTC, dornp commented on source/index.html
> +        <h2 class="secondary-title">Живой пример</h2>
👍

2023-04-03 10:17 UTC, dornp commented on source/index.html
> +        </div>
👍

2023-04-03 10:17 UTC, dornp commented on source/index.html
> +        <div class="address address--size-small">
👍

2023-04-03 10:18 UTC, dornp commented on source/index.html
> +        <img class="address-map__map-image" src="img/location.png" width="320" height="362" alt="Наше местоположение">
👍

2023-04-03 10:20 UTC, dornp commented on source/index.html
> +      <img class="logo-title" src="img/logo-title.svg" width="101" height="18" alt="Cat energy title">
👍

2023-04-03 10:24 UTC, dornp commented on source/index.html
> +      <div class="footer__social social">
👍

2023-04-03 10:24 UTC, dornp commented on source/index.html
> +              <span class="visually-hidden">youtube</span>
👍

2023-04-03 10:25 UTC, dornp commented on source/index.html
> +      </div>
👍

2023-04-03 10:29 UTC, dornp commented on source/catalog.html
> +            <li class="main-nav__item main-nav__item--current">
👍

2023-04-03 10:37 UTC, dornp commented on source/catalog.html
> +        <li class="product-card">
Я не понимаю... те карточка - это ссылка на страницу конкретного товара? У нас такой стр нет, просто сделать `<a href="#">карточка продукта<a>`?

2023-04-03 10:41 UTC, dornp commented on source/catalog.html
> +          <span class="product-card__title">Cat Energy PRO 500 г</span>
👍

2023-04-03 10:43 UTC, wrgraff commented on source/catalog.html
> +        <li class="product-card">
Да, как-то так, у нас просто не полный макет.
Про это даже есть [пункт в ТЗ](https://up.htmlacademy.ru/adaptive/28/project/cat-energy#cat-energy-6-1)

_Кстати, тут есть ТЗ в отличие от первого уровня_

2023-04-03 11:00 UTC, dornp commented on source/catalog.html
> +        <li class="product-card">
Хорошо, спасибо 👍

2023-04-03 11:24 UTC, dornp commented on source/catalog.html
> +          <button class="primary-button product-card__button" type="button">Заказать</button>
👍

2023-04-03 11:27 UTC, dornp commented on source/catalog.html
> +          <span>На самом деле вкусов гораздо больше!</span>
👍

2023-04-03 11:30 UTC, dornp commented on source/catalog.html
> +      <div class="extra-product-catalog">
👍

2023-04-03 11:31 UTC, dornp commented on source/catalog.html
> +            <span class="extra-product-card__title">Сахарозаменитель</span>
👍

2023-04-03 14:26 UTC, dornp commented on source/catalog.html
> +            </table>
👍

2023-04-03 14:27 UTC, dornp commented on source/catalog.html
> +        </div>
👍

2023-04-03 14:30 UTC, dornp commented on source/form.html
> +      <p class="call-to-action-phrase">
👍

2023-04-03 17:26 UTC, dornp commented on source/form.html
> +      <p class="call-to-action-phrase">
👍

2023-04-04 16:17 UTC, wrgraff commented on source/catalog.html
> +        <img class="logo-text" src="img/logo-title.svg" width="101" height="18" alt="Cat energy">
Не, ну если так, то можно сделать отдельный блок `logo`, а то получается у нас сразу 2 блока создается.
```suggestion
      <a href="index.html" class="header__logo logo">
        <img class="logo__icon" src="img/logo-mobile.svg" width="33" height="37"
          alt="Cat energy" aria-hidden="true">
        <img class="logo__text" src="img/logo-title.svg" width="101" height="18" alt="Cat energy">
```

2023-04-04 16:17 UTC, wrgraff commented on source/index.html
> +        <button class="main-nav__toggle main-nav__toggle--active" type="button">
Ну да, логично =)
Но мы пока еще не очень решили как именно будем показывать и прятать меню, там еще может и обертка какая-то понадобится, и декор всякий и зависимость между кнопкой и меню... Мы все это продумаем, но все же попозже

2023-04-04 16:48 UTC, wrgraff requested changes
Проблем почти не осталось, не принял только потому что есть техническая опечатка по БЭМу

2023-04-04 16:48 UTC, wrgraff commented on source/index.html
> +        <h1 class="hero_title main-title">Функциональное питание для котов</h1>
Кажется, элемент посеял один символ в нейминге.
Кстати, чисто технические недочеты по неймингу можно проверять [в инструменте от Йоксель](https://yoksel.github.io/html-tree/)

```suggestion
        <h1 class="hero__title main-title">Функциональное питание для котов</h1>
```

2023-04-04 16:48 UTC, wrgraff commented on source/index.html
> +          <a class="program__link" href="#">Каталог Slim</a>
Ну ссылки вроде норм были. Допустимо в верстке, где у нас нет реального контента, но есть аналогичные страницы, то можно на них ссылку делать для удобства.

Например, с любой карточки товара попадаем на одну и ту же html-страницу с шаблоном товара. Это обычная практика.

2023-04-04 16:48 UTC, wrgraff commented on source/index.html
> +        <section class="program">
Для единообразия. Мы как бы одинаковым подходом размечаем каждую из секций. Так можно придумать более универсальный паттерн для секций и переиспользовать его. Чтобы настраивать и менять что-то по необходимости в одном месте, а не в каждом отдельно.

И еще есть такой аргумент: если в дизайне есть хоть одна секция с тянущимся фоном и центрированным  контентом, то в таком стиле может быть переоформлена и любая другая секция.

В общем, единообразие дает преимущества, особенно для живого и масштабируемого проекта. У нас конечно не такой проект, но применять подход можно и уже сейчас =)

2023-04-04 16:48 UTC, wrgraff commented on source/catalog.html
> +            <a href="#" class="primary-button extra-product-card__button">Заказать</a>
С вложенностью немного путаница вышла
```suggestion
            <h3 class="extra-product-card__title">Сахарозаменитель</h3>
            <dl class="extra-product-card__table">
              <dt class="visually-hidden">Объем</dt>
              <dd class="extra-product-card__data">1 упаковка (100 г)</dd>

              <dt class="visually-hidden">Цена</dt>
              <dd class="extra-product-card__data">200 &#8381;</dd>
            </dl>

            <a href="#" class="primary-button extra-product-card__button">Заказать</a>
```

2023-04-04 16:48 UTC, wrgraff commented on source/index.html
> +        </div>
Можно же один список сделать ))
Фокус в том, что в отличие от `ul` и `ol` в этом виде списка можно пары дополнительно оборачивать дивами.

```suggestion
        <dl class="example__result-data-wrapper">
          <div class="result-data">
            <dt class="result-data__parameter">5 кг</dt>
            <dd class="result-data__descr">Снижение веса</dd>
          </div>

          <div class="result-data">
            <dt class="result-data__parameter">60 дней</dt>
            <dd class="result-data__descr">Затрачено времени</dd>
          </div>
        </dl>
```

2023-04-04 16:48 UTC, wrgraff commented on source/index.html
> +        </div>
Я конечно может зря сразу не сказал обратить внимание, но `dt` — это то, что мы определяем, а `dd` — это значение.
Тут скорее должно быть наоборот, например "Снижение веса" это `dt`, а "5 кг" уже `dd`.

Здесь кроется и второй подвох. В разметке обязательно сперва должен идти `<dt>`.
Итого получается, что нам нужно в разметке поставить их в обратном порядке. А уже потом стилями расположить как нам надо визуально.

2023-04-04 16:49 UTC, wrgraff commented on source/catalog.html
> +      <a class="footer-logo logo" href="#">
```suggestion
      <a class="footer__logo logo" href="#">
```

2023-04-05 08:24 UTC, wrgraff approved these changes

2023-04-05 08:24 UTC, wrgraff commented on source/index.html
> +          <a class="primary-button hero__button" href="form.html">Подобрать программу</a>
Заметил разный порядок, иногда сперва классы блока, потом элемента, иногда — наоборот.
Надо писать всегда в одном порядке (сейчас в каком тебе больше нравится, а на настоящем проекте могут потребовать как принято)

2023-04-05 08:24 UTC, merged