Стилизация
htmlacademy-adaptive/2280491-cat-energy-28 pull request #3
Opened 2023-04-07 12:57 UTC by dornp

2023-04-08 18:53 UTC, wrgraff requested changes
Очень много сделано работы с забеганием вперед. Это может вызывать проблемы.

Работа содержит ошибки и недочеты, которые формально относятся к будущим темам, которые еще не разобраны авторами и по которым пока что не даны материалы. Если я начну их все подробно разбирать, то придется в комментариях пытаться описать то, о чем есть целые лекции и статьи в материалах курса. Естественно, я не смогу подать это во всей полноте.
Да и так возрастает количество кода, который придется переписывать.

Кроме того, это и проверку пул-реквеста затрудняет, так как она становится объемнее.

Лучше отправляй задания чаще, но меньшими частями. И не забегай больше так далеко вперед, пожалуйста.

2023-04-08 18:53 UTC, wrgraff commented on source/catalog.html
> +        <a href="#" class="page-header__logo logo">
А почему пропала ссылка на главную?

2023-04-08 18:53 UTC, wrgraff commented on source/index.html
> +        <nav class="page-header__main-nav main-nav visually-hidden">
Нельзя скрывать переключаемые элементы через доступное скрытие.

Доступное скрытие нужно для того, чтобы элемент оставался виден при чтении скринридерами. Это значит, что все интерактивные элементы внутри `visually-hidden` будут фокусироваться с клавиатуры, чего с меню происходить не должно.

Доступность меню работает по иному принципу. Оно скрыто недоступно, но после открытия становится и видимо и доступно. Для этого и обычный `display: none` подходит.

Кроме того, пока нет подключенного js, меню должно быть открыто и находиться в потоке.

2023-04-08 18:53 UTC, wrgraff commented on source/index.html
> +        <a class="page-footer__logo" href="#">
А почему нет адреса ссылки

2023-04-08 18:53 UTC, wrgraff commented on .stylelintrc
> +    "at-rule-no-unknown": null
При тестировании во время сдачи проекта может использоваться оригинальный файл с правилами стилей от Академии. В таком случае это тестирование твой проект может и не пройти

2023-04-08 18:53 UTC, wrgraff commented on source/catalog.html
> +            <a class="product-card__product-link" href="#">
А зачем 2 раза писать `product`? У нас уже обозначено в названии блока что это карточка продукта, соответственно и в класс элемента это попадает:
```suggestion
            <a class="product-card__link" href="#">
```

2023-04-08 18:53 UTC, wrgraff commented on source/catalog.html
> +        <h1 class="page-main__title main-title page-main__title--catalog">Каталог продукции</h1>
Странный порядок классов. Раз уж сперва идет элемент, то и его модификатор должен быть следом
```suggestion
        <h1 class="page-main__title page-main__title--catalog main-title">Каталог продукции</h1>
```

2023-04-08 18:53 UTC, wrgraff commented on source/sass/fonts.scss
> +  src: url("../fonts/lato/Lato-Regular.woff2") format("woff2");
В названиях файлов и папок нам нужно придерживаться нижнего регистра. Дело в том, что некоторые операционные системы учитывают регистр, а некоторые нет.

Может случиться так, что работал ты в системе, что регистр не учитывает, а проект опубликован в той, что учитывает. И тогда у тебя все будет работать, несмотря на разные буквы, а в опубликованной версии — нет. И это будет совсем не здорово.

Поэтому разработчики условились всегда называть файлы и папки в нижнем регистре (на самом деле нет, но пока ограничимся этим).

> Может случиться так, что изменения регистра не попадают в коммит, как раз из-за того, что система разницы между этими названиями не видит.
Верный способ решить это по простому: кроме смены регистра переименовать файл как-то более заметно (добавить цифру 0, например), закоммитить и затем удалить ненужный символ и еще раз закоммитить. Так изменения точно попадут в коммит.

2023-04-08 18:53 UTC, wrgraff commented on source/sass/style.scss
> +// Common little blocks
Деление файлов на группы противоречит принципам БЭМа, так как независимость предполагает, что блоки вообще не знают где они находятся и могут быть встроены в любом месте сайта.

Кроме того, БЭМ-блоки невозможно отнести к одной категории. Например, какие могут быть гарантии, что на основной странице каталога не окажется блок `blocks/index-blocks/program.scss`?
Или наоборот: а что, если слайдер с товарами `blocks/catalog-blocks/product-card.scss` решат добавить на главную?

В процессе существования сайта такие логические привязки блоков скорее запутают и будут мешать. Как это ни странно, но найти блок в одной папке удобнее всего (тем более, они отсортированы редактором кода по алфавиту)

2023-04-08 18:53 UTC, wrgraff commented on source/sass/style.scss
> +@use "variables" as v;
В этом файле переменные не используются же

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/base.scss
> +.page__body {
`.page__body` это элемент блока `page`, соответственно стили для этого класса должны находиться в файле `blocks/page.scss`

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/base.scss
> +.visually-hidden {
Формально это файл для блока `base`. Но его не существует.

Скорее всего, это файл для базовых стилей, которые не относятся к БЭМ-блокам. Тогда его нужно вытащить из папки `blocks`

2023-04-08 18:53 UTC, wrgraff commented on source/sass/_variables.scss
> +$color-light: #ffffff;
Есть 2 распространенных подхода именовать цвета. Здесь больше похоже на именованные цвета. Логика в том, что мы создаем переменные для цветов с учетом их применения: цвета для текста, фона, плашек, рамок и прочее. Лучше всего это работает тогда, когда дизайнер заложил такой подход в дизайн-систему. Так некоторые переменные будут повторять цвета. Зато это хорошо работает для создания тем.
В таком подходе вряд ли может быть цвет `$color-light`, так как непонятно какое его назначение.

Другой вариант — создать [палитру цветов](https://frontend-design.notion.site/a8b8c114d0dc40aab87a54e8cc8dd859).

2023-04-08 18:53 UTC, wrgraff commented on source/sass/_variables.scss
> +@mixin block-center {
Если делать миксы, то я бы рекомендовал выделить для них отдельный файл `_mixins.scss`, так как технически они не являются переменными и применяются совсем иначе.

2023-04-08 18:53 UTC, wrgraff commented on source/sass/_variables.scss
> +}
На самом деле, БЭМ и сам неплохо справляется с миксованием через классы. Например, можно создать БЭМ-блок `.button` и стилизовать с его помощью все кнопки.
Аналогично и вместо `block-center` можно создать какой-то класс (обычно это `wrapper` или `container`).

То есть, если набор стилей выполняет одну задачу (центрирует, стилизует кнопку), то имеет смысл выделить его в БЭМ-блок.
На CSS-миксы можно оставить то, что выполняет какую-то часть работы. Например, сбросить стили списка или филдсета (как `list-reset` и `form-reset`), потому что в 90% случаев нам будет необходимо добавить оформления.

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/address.scss
> +  font-family: "Oswald", sans-serif;
Обычно как раз для `font-family` создают переменную, чтобы при смене шрифта можно было его изменить из одного места

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/address.scss
> +  display: flex;
В этом задании нужно было расставить шрифтовые параметры, цвета и _некоторые и отступов_.
Сетки — большое забегание вперед!

Кроме того, на этом курсе стоит особое внимание уделить гридам (и именно с них начнутся адаптивные сетки), так как они позволяют решать задачи по раскладке гораздо эффективнее

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/catalog-blocks/extra-product-card.scss
> +  color: #222222;
Немного странно, конечно, что у нас цвета не в переменных, а размер шрифтов в переменных...

Вероятность того, что нам по всему сайту 14-е шрифты надо будет поменять на 15-е довольно мала.
Правда, вероятность того, что придется сменить все цвета `#222222` на `#333333` тоже мала. Но чуть выше, чем со шрифтами =)

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/social-list.scss
> +    background-image: url("../../img/socials/vkontakte.svg");
Неправильный путь к файлу. Препроцессор не умеет при сборке переписывать пути к картинкам. Это обычная статическая строка. Поэтому нам нужно писать путь исходя из того, где находится наш скомпилированный css-файл.

У нас директория `img` находится обычно рядом с директорией `css`, а значит нужно один раз выйти из директории(`../`) и зайти в картинки.

> Почему же при всем при этом картинки работают?
Потому, что лишние выходы на уровень выше не срабатывают, так как мы сразу попадаем в корневую директорию. Однако, если мы сделаем тоже самое на сервере с другими настройками, то будет проблема. Например, попробуй опубликовать свой пул-реквест в интерфейсе проверки задания (прямо в интерфейсе Академии есть такая кнопка)

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/catalog-blocks/present.scss
> +  height: 290px;
БЭМ-блокам нельзя задавать размеры и внешние отступы.
Основная идея блока в том, что он переиспользуемый, а значит должен подстраиваться под контент в зависимости от контекста.

Например, у нас есть БЭМ-блок `.card` в виде карточки товара. И есть страница с карточками товаров, где в сетке товаров каждая карточка занимает в ширину 320 пикселей.
Мы задаем БЭМ-блоку `.card` ширину 320 пикселей: а что такого?

![https://user-images.githubusercontent.com/37917037/127750217-6f72b53c-d8ce-402b-b342-0cbe69453432.png](https://user-images.githubusercontent.com/37917037/127750217-6f72b53c-d8ce-402b-b342-0cbe69453432.png)

Но на другой странице мы встречаем боковой список товаров, где конечно же будет логично использовать наш блок `.card` снова. Ставим его туда, и наша сетка "едет": оказывается, там меньше места, и нам нужна карточка 280 пикселей шириной. Но из-за заданного размера карточка "торчит" из контейнера.

![https://user-images.githubusercontent.com/37917037/127750221-7c75880d-5832-4b36-acc4-a071c24fc080.png](https://user-images.githubusercontent.com/37917037/127750221-7c75880d-5832-4b36-acc4-a071c24fc080.png)

Поэтому у блока размеров быть не должно: БЭМ-блок `.card` должен подстроиться под ширину кониейнера или колонки, в котором он находится: эти размеры определяются тем контекстом, в котором мы его используем.

Аналогичная ситуация и с отступами (но пример с размером более нагляден). Отступы так же должны быть определены контекстом, в котором использован БЭМ-блок: через элементы или gap'ы в сетке. Блок не должен ничего сдвинуть или сместить в своем окружении.

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/catalog-blocks/present.scss
> +  height: 290px;
Здесь надо отметить, что на защите тебя по этим нюансам проверять не будут, потому что в академии ограничиваются проверкой нейминга и файловой структуры по БЭМ.

Поэтому, тебе нужно будет сообщить мне — хочешь ли ты попробовать по максимуму соответствовать принципам БЭМ, или же, если это пока кажется сложным, мы можем ограничиться более простыми правилами (ты так же можешь отказаться от соблюдения этого позже, если станет тяжело).

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/catalog-blocks/present.scss
> +  margin: 0;
Есть проблема не только с установкой, но и с обнулением отступов у БЭМ-блоков. Хотя, казалось бы обнуление — это же не установка отступа, а удаление?..

Но суть проблемы в том, что обнуление внутри блока точно так же может случайно переписать свойства элемента, как и указание какого-то конкретного размера.
Потому что технически мы не обнуляем, а назначаем отступ, равный нулю. Поэтому даже обнуления придется делать через элементы.

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/catalog-blocks/present.scss
> +    display: block;
Тут это правило ничего не дает, так как его все равно переопределяют 2 фактора:
1. во flex-контейнере все потомки становятся flex-элементами, и поэтому не важно какое у них отображение
2. при `position: absolute;` все элементы ведут себя как блочные

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/catalog-blocks/present.scss
> +    top: 59px;
Вот опять же, огромное забегание вперед!
Такие картинки вообще относятся к декоративным элементам. У нас еще нет адаптивной сетки, неизвестно как этот блок будет перестраиваться. Рано делать выводы о том, как лучше реализовать декор: через абсолютное позиционирование, как часть потока или вообще дополнительным слоем фона.

Зачем настолько вперед идти? Это +3 раздела

2023-04-08 18:53 UTC, wrgraff commented on source/sass/blocks/catalog-blocks/product-card.scss
> +}
Чаще всего делается общий блок `button`, который в зависимости от модификаторов может менять размер и цвет. То есть, у нас не 5-6 разных кнопок, а одна кнопка 5-6 разных видов.

Модификатор `--last-card` тоже не выглядит очень подходящим. На самом деле ведь логика не заключается в том, что в последней карточке нам нужна кнопка другого цвета. Эта карточка вообще другого вида (стоит кстати подумать о том, чтобы не делать ее как блок `product-card`, она не имеет с карточкой продукта ничего общего, а лишь стоит с ними в одном списке).

2023-04-09 07:51 UTC, dornp commented on .stylelintrc
> +    "at-rule-no-unknown": null
Дело в том, что тогда `@use`, не будет работать, у многих такая проблема. Lint подчёркивает `@use` как ошибку.

2023-04-09 16:20 UTC, dornp commented on source/sass/blocks/catalog-blocks/present.scss
> +    top: 59px;
ok, я переделаю потом

2023-04-10 09:29 UTC, wrgraff commented on .stylelintrc
> +    "at-rule-no-unknown": null
Я вообще не уверен, что на таком проекте нужен `@use`. Не совсем понятно какую пользу он несет на проекте такого плана. Можешь как-то обосновать, почему именно через `@use` используется подключение, а не через обычное подключение файла с переменными?

2023-04-10 12:52 UTC, wrgraff requested changes
Есть еще проблемка с путями и с переименованием файла

2023-04-10 12:52 UTC, wrgraff commented on source/sass/fonts.scss
> +  src: url("../fonts/lato/lato-regular.woff2") format("woff2");
Насколько я вижу, файл сам не переименован

2023-04-10 12:52 UTC, wrgraff commented on source/sass/_variables.scss
>  $text-color-primary: #000000;
Я бы так как серый назван как `gray`, то и эти бы смело и понятно называл:
```scss
$white-color: #ffffff;
$black-color: #000000;
```

2023-04-10 12:52 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
>    background-image: url("../../img/academy-logo.svg");
Я там в одном месте написал про пути, но перепроверить их везде надо: ошибка повторяющаяся

2023-04-10 13:53 UTC, dornp commented on source/sass/fonts.scss
> +  src: url("../fonts/lato/lato-regular.woff2") format("woff2");
Это git не увидел изменения регистра.

2023-04-10 15:25 UTC, wrgraff approved these changes

2023-04-10 15:25 UTC, merged

2023-04-10 15:37 UTC, wrgraff commented on source/sass/fonts.scss
> +  src: url("../fonts/lato/lato-regular.woff2") format("woff2");
Да, поэтому я отдельно писал как с этим справиться =)