Адаптивная сетка
htmlacademy-adaptive/2280491-cat-energy-28 pull request #4
Opened 2023-04-13 15:55 UTC by dornp

2023-04-13 21:32 UTC, wrgraff requested changes
Так, ну работа хорошая, местами прям порадовала.
Тут — часть ревью, другая часть придет в Телеграм в 9 утра завтра: я по сеткам традиционно делаю видео-ревью, потому что текстом сложно описывать почему элемент при каких-то манипуляциях ведет себя нехорошо. Почти асинхронная консультация получается )

2023-04-13 21:32 UTC, wrgraff commented on source/index.html
> +          <h1 class="hero__title main-title">Функциональное<br>питание для котов</h1>
Я бы предложил не использовать переносы строк на данном этапе.

Дело в том, что форматированный текст ведет себя иначе и сразу же оказывается удобной для нас ширины, создавая ложное впечатление. А нам нужно бы убедиться, что он подстраивается под сетку вне зависимости от форматирования самого текста, так как на настоящих сайтах приходят контент-менеджеры и меняют тексты, без всякого форматирования.

В теории, может выйти и так, что если переносы убрать, то сетка развалится.

Мы потом сможем поставить переносы, если это будет нужно (после модуля сеток).

2023-04-13 21:32 UTC, wrgraff commented on source/sass/_mixins.scss
> +@mixin form-small-text-big-screen {
Название тут уже само по себе неплохой показатель того, что миксин этот не самый удачный... Слишком специфично выглядит, а миксин должен быть по идее таким, чтобы был чуть ли не в каждом втором файле нужен

2023-04-13 21:32 UTC, wrgraff commented on source/sass/_variables.scss
> +$desktop-width: 1220px;
Немного экскурса в терминологию =)

Вьюпорт — это видимая пользователем область в окне браузера. То есть, он включает в себя ширину и высоту.
То есть, это уже не совсем то, что мы здесь указываем.

Как вообще используются переменные `$tablet-width`  и `$desktop-width`? Это значения, при которых меняется режим отображения. Такое обычно называют `breakpoint`.

Второе, что мне никогда не нравилось в этом подходе, это деление на мобильный, планшет и десктоп. С современными устройствами диапазоны размеров экранов такие, что планшетная версия может оказаться на телефона, а десктопная — на планшет. Кажется, что логичнее было бы абстрактное `small / medium / large`.
Кроме того, сайтам иногда нужно не 3 версии, а больше. И тогда абстрактным величинам проще добавлять в имена точек: `x-small / small / medium / large / x-large`

2023-04-13 21:32 UTC, wrgraff commented on source/sass/blocks/about.scss
> +@media (min-width: v.$desktop-width) {
Разве не удобнее медиа-запросы писать внутри классов?

Это получается если я работаю с адаптивом элемента `.about__item`, то возможно надо будет переключаться с 16 строки на 90. И это пока что, дальше они еще расползутся

2023-04-13 21:32 UTC, wrgraff commented on source/sass/blocks/address-map.scss
>  @use "mixins" as m;
Тут вроде и миксинов то нет...

2023-04-13 21:32 UTC, wrgraff commented on source/sass/blocks/extra-product-card.scss
> +    box-sizing: border-box;
Как по мне, поведение блока, которое влияет на формирование его размеров менять от элемента к элементу, а тем более для разных разрешений экрана — идея сомнительная.

Я за то, чтобы [прописать его один на проект](https://telegra.ph/box-sizing-04-13).

2023-04-13 21:32 UTC, wrgraff commented on source/sass/blocks/extra-product-card.scss
> +  // }
В пул-реквесте могут быть комментарии, а вот закомментированного кода быть не должно. Это подходящий способ для того, чтобы что-то временно проверить, но пул-реквест — это отправка предположительно рабочего кода, который в идеальном случае должен попасть в рабочий проект. Поэтому код в нем должен быть только нужный и актуальный

2023-04-13 21:32 UTC, wrgraff commented on source/sass/blocks/social-list.scss
>  @use "mixins" as m;
Если мы что-то импортируем (`@import` ли это или `@use`), то оно должно использоваться.
А если использования нет в файле, то и импорт не нужен.

"Про запас" их делать не надо =)
Понадобилась переменная — добавили, убрали использование миксов из файла — и импорт убрали

2023-04-16 17:34 UTC, dornp commented on source/sass/blocks/address-map.scss
>  @use "mixins" as m;
Уже есть :)

2023-04-18 15:22 UTC, wrgraff requested changes
Нужно еще подправить несколько мелких технических моментов. Мелких, но важных.
А так отлично

2023-04-18 15:22 UTC, wrgraff commented on source/index.html
> +          </button>
А зачем лишняя табуляция появилась?
Тут можно попасться на базовый критерий [Б28](https://up.htmlacademy.ru/adaptive/28/criteries#b28)

2023-04-18 15:22 UTC, wrgraff commented on source/index.html
> +          <div class="address-map__address address wrapper">
Не уверен, что тут хорошо будет работать общий класс `wrapper`. Но посмотрим.

Футер странно работает, описание не центрируется и залезает под карту.
<img width="2177" alt="изображение" src="https://user-images.githubusercontent.com/37917037/232810776-9dd064c2-cfa7-4227-ac38-bc8982569ccf.png">

Вообще, у меня есть [для похожей ситуации любопытное решение](https://youtu.be/Ccmu3wrjY8o), которое работает с переполнением. Оно для другого сайта и без адаптива, но можно применить такой же подход для десктопа.

2023-04-18 15:22 UTC, wrgraff commented on source/sass/_mixins.scss
> +}
Очень хороший пример того, как именно по настоящему могут быть полезны миксы.

Его еще усложнить можно, чтобы он работал с конкретными цифрами и мог вставлять как `min-width`, так и `max-width`, если мы хотим сделать медиа-запрос не вверх от значения, а вниз.
Сейчас лучше не заморачиваться, но если хочешь, могу скинуть как это выглядит

2023-04-18 15:22 UTC, wrgraff commented on source/sass/_variables.scss
>  // Viewports
Тогда уж так )
```suggestion
// Breakpoints
```

2023-04-18 15:22 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +  @include m.breakpoint(medium) {
Начиная с планшета уже требуется ограничивать ширину:
<img width="1118" alt="изображение" src="https://user-images.githubusercontent.com/37917037/232819065-58658bbc-7112-4776-897c-f97e3f0f7b26.png">

2023-04-18 15:22 UTC, wrgraff commented on source/sass/blocks/hero.scss
> +  box-sizing: border-box;
Уже везде вроде бы прописано такое поведение, можно внутри убрать

2023-04-18 15:22 UTC, wrgraff commented on source/sass/blocks/hero.scss
> +  padding: 7px 0;
Не лучшее "разделение обязанностей" между БЭМ-блоком `button` и БЭМ-элементом `hero__button`.

Когда мы миксуем элемент и блок, то лучше всего через элемент задавать размеры, внешние отступы и положение в сетке. А все, что "внутреннее" — оставить блоку.
То есть, чтобы поменять размер кнопки, шрифт, цвет и прочее, лучше завести модификатор для `button`.

---

Почему плохо смешивать задаваемые стили и не стоит менять свойства, заданные блоку, через элемент?
Мы так создадим зависимости между разными блоками. Например, если элемент `hero__button` переписывает свойства `button`, то стили блока `hero` обязательно должны подключаться после `button`, иначе они не перезапишут эти значения.
Здесь кажется, что это не так уж и страшно — всего то надо подключить `button` повыше. Но будут и более сложные примеры и ситуации, которые могут привести к неразрешимой проблеме, где 3 блока должны переназначать друг друга. А еще такие связи не видны явно и их будет очень трудно отслеживать.

_Правда, для одного-двух блоков с особой функцией можно сделать и исключение. Например, `wrapper` выполняет определенную роль по всему проекту, но если нужно будет в одном блоке это поведение поменять, то мы это сделаем легко, если wrapper переназначается_

2023-04-18 15:22 UTC, wrgraff commented on source/sass/blocks/order-form.scss
> +    max-height: 52px;
Немного странное ограничение. А вдруг там будет огромный текст, который будет в 2 строки?

Лучше создавать кнопкам формирование размеров через отступы.

2023-04-18 15:22 UTC, wrgraff commented on source/sass/blocks/page.scss
> +  box-sizing: border-box;
Кажется, теперь точечные назначения стали лишними

2023-04-18 19:10 UTC, dornp commented on source/index.html
> +          <div class="address-map__address address wrapper">
Общий класс wrapper я удалила, тк уже 5 задание начала немного делать, сделала iframe. Здесь блок адреса залезает под карту, тк он position absolute, я сделаю в следующем дз блок адреса на карте. Видео посмотрела, буду пробовать.

2023-04-18 19:20 UTC, wrgraff commented on source/index.html
> +          <div class="address-map__address address wrapper">
Понял, учел!

2023-04-19 13:32 UTC, dornp commented on source/sass/_mixins.scss
> +}
Да, скинь, если не сложно)

2023-04-19 17:51 UTC, wrgraff approved these changes

2023-04-19 17:51 UTC, wrgraff commented on source/sass/blocks/page-header.scss
> +    margin: 0 auto;
А зачем еще раз задавать `margin`? Он уже задан для планшета.
У нас же эти медиа-запросы работают от указанной точки и выше: десктоп больше планшета, поэтому он получит все его стили

2023-04-19 17:51 UTC, merged

2023-04-19 18:01 UTC, dornp commented on source/sass/blocks/page-header.scss
> +    margin: 0 auto;
Убрала