Адаптивные декоративные элементы
htmlacademy-adaptive/2280491-cat-energy-28 pull request #5
Opened 2023-04-24 11:15 UTC by dornp

2023-04-24 11:18 UTC, dornp commented
Посмотри, пожалуйста, как отображается карта в десктопной версии.

2023-04-25 19:12 UTC, wrgraff requested changes

2023-04-25 19:12 UTC, wrgraff commented on source/index.html
> +                </span>
Как-то после закрытого тега текст плохо видно. Я вот не сразу понял зачем 2 обертки вокруг текста, не увидел его =)
Можно так:
```suggestion
                <span class="example__costs">
                  <span class="example__costs-text">
                    Затраты на питание:
                  </span>
                  15 000 &#8381;
                </span>
```

Или покомпактнее:
```suggestion
                <span class="example__costs">
                  <span class="example__costs-text">Затраты на питание:</span>
                  15 000 &#8381;
                </span>
```

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/about.scss
> +      content: "1";
Было бы здорово применить не конкретные цифры к конкретным пунктам, а использовать порядковый номер. Хорошо подойдет реализация с помощью [счетчика CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters)

При чем, нам действительно стоит разделить логику, по которой создается порядковый номер и по которой добавляется иконка. Ведь если в разметке поменять местами пункты, то картинка должна переехать (и она переедет, если добавлена через модификатор), а вот цифра должна по прежнему показывать порядковый номер.

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/about.scss
> +      @include m.number-about;
Эх, хочется использовать миксины, но...

В чем тут проблема?
Вроде бы в файле выглядит аккуратно: добавили к каждому модификатору блок кода из микса.
По факту в CSS-файле в каждом модификаторе развернется блок кода, указанный в миксине. Это код, повторенный 4 раза (для 4 иконок).

Альтернатива: не вставлять микс, а написать этот код для базового класса элемента `.about__item`. Тогда этот код тоже будет работать в каждом элементе, но фактически в CSS-файле будет только единожды использован

2023-04-25 19:12 UTC, wrgraff commented on source/img/mail.svg
Очень здорово, что иконки экспортированы не самой фигурой, а внутри области.
В дизайне позиционируется именно контейнер, содержащий иконку, а иконка в нем центрирована. Такой экспорт избавит от необходимости подгонять каждую иконку отдельно, очень грамотное решение

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/address-map.scss
> +    z-index: -1;
Отрицательный `z-index` загонит карту под все элементы, а у нас тут есть доп обертка. Лучше его не задавать отрицательный, а напротив можно даже задать 1.
И задать `z-index: 2` для `.address__wrapper`, так как только этот белый прямоугольник должен быть над картой.

Да, мы наделаем так слоев, но благодаря индексу для `.address-map` все они будут только в контексте карты.

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/address.scss
> +    pointer-events: none;
Тут просто помечу комментом, что от этой штуки стоит избавиться: мало ли нам какой-то интерактив понадобится: такой стиль может подбросить проблем.
Но после решения вопроса со слоями карты он нам и не нужен будет.

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +  display: block;
Когда `position: absolute;` элемент всегда ведет себя как `display: block;`.
Ну это так, для справки =)

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +.checkbox__input:checked + .checkbox__text::after {
Учитывая, что единственное, что добавляется при отмеченном элементе — это галочка, я бы не создавал второй псевдоэлемент, а добавил бы фон для `.checkbox__text::before`

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +.checkbox__input + .checkbox__text::before {
Вроде можно обойтись тут и более простым селектором же )
```suggestion
.checkbox__text::before {
```

Через `+` нам надо выбирать обязательно только из-за того, что нужно проверить состояние

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/example.scss
> +    &::after {
А еще это можно решить с помощью градиента.
Не обязательно, конечно, но кое в чем градиент будет лучше: он не создаст в DOM-дереве страницы элемент (а псевдоэлемент с точки зрения отрисовки все-таки элемент). Чем меньше элементов — тем лучше производительность.

Хотя, с таким сайтиком производительность конечно не должна быть проблемой в целом

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  }
Можно еще выставить ему `opacity: 1`, так как некоторые браузеры меняют интенсивность плейсхолдера через прозрачность

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  }
Тут проблема в том, что эти элементы должны будут менять цвет при наведении.
Впрочем, это отчасти следующее задание. Но нам почти наверняка придется кое-что тут переделать в ближайшем будущем: имей ввиду

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/form-programs.scss
> +    width: 100vw;
Расчет верный, но к сожалению не может быть всегда точным, так как по какой-то странной причине `100vw` включает в себя еще и ширину скроллбара.

Тут нужно кой-чего пофиксить, я наверное запишу на эту тему скринкаст, чтобы не расписывать огромный текст с 10 скриншотами

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/order-form.scss
> +    border: 2px solid v.$brand-color-400;
Если делать рамку в 2 пикселя, то получается визуальная полоска в 4 пикселя, потому что есть рамка верхняя и нижняя.
Обычно такие элементы делают как прямоугольники (так ими проще управлять, получаются более предсказуемые размеры) с фоном и высотой в нужное количество пикселей

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/order-form.scss
> +    top: 50%;
Думаю, имеет смысл рассмотреть вариант расположения не 50%, а какое-то конкретное количество пикселей, так как эта полоска должна быть на середине первой строки (мы это видим по двустрочному заголовку). А первая строка, каким бы большим ни был текст, всегда будет на одном уровне.

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/page.scss
> +        url("../img/cat-large.png");
Надо бы отключить повторение кота:
<img width="1134" alt="изображение" src="https://user-images.githubusercontent.com/37917037/234375456-3d2a3631-c730-4625-bf07-4a6ecc82d1f4.png">

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/product-card.scss
> +  }
Есть ощущение, что у этих модификаторов настолько разные стили, что это разные БЭМ-элементы по своей сути.
Что и то и другое ссылка — только совпадение по тегу, а визуально (за то, за что отвечает БЭМ и классы) они совсем не похожи

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/product-card.scss
> +      height: 430px;
Фиксированная высота не лучший вариант, так как если у нас появится больше строк в таблице характеристик, эта плашка сползет вниз.
Можно попробовать фокус с одновременным заданием `top` и `bottom`, хот и здесь предпочтительнее фоном сделать

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/radio.scss
> +  left: 8.5px;
Такого не бывает, чтобы в верстке были половинчатые значения.
На экране нет полупикселей (разве что там ретина, но это не факт и не факт, что там ровно вдвое выше плотность) и такие значения гарантированно дадут на многих экранах "мыльную" картинку.

Понимаю, что это следствие реализации в дизайне:
<img width="291" alt="изображение" src="https://user-images.githubusercontent.com/37917037/234377346-b30bec25-7192-47d8-9275-f3e53d26db8b.png">
Но это — на 100% ошибка дизайнера, он не должен был так делать. Мы можем сделать центральный кругляк на пиксель больше или пиксель меньше, чтобы расстояние до краев было в целых пикселях. Да, в ПП мы на пол пикселя не попадем, но это допустимо

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/show-more-card.scss
> +    margin-top: 160px;
Лучше место под декор резервировать внутренним отступом, так как у нас нет гарантий, что `.show-more-card__title` будет всегда и его не заменят на какой-нибудь другой элемент или не удалят, оставив только текст

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/show-more-card.scss
> +  }
Можно было бы и просто поместить эту иконку в фон элемента, чтобы не создавать лишних элементов в DOM'е

2023-04-25 19:12 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +  }
Это же ползунок, за который можно потянуть чтобы поменять вид элемента.
Надо бы его в разметку поместить как какую-нибудь кнопку, чтобы можно было за него хвататься мышкой

2023-04-25 19:13 UTC, wrgraff commented
Ответ про карту есть в одном из комментариев. В целом отличная работа!

2023-04-27 16:31 UTC, wrgraff requested changes
Есть несколько деталей, вроде бы мелких, но из-за них можно не пройти защиту.
Поправить их получится быстро =)

2023-04-27 16:31 UTC, wrgraff commented on source/index.html
> +              <button class="slider__button" type="button"></button>
Подпись для интерактивных элементов обязательна

2023-04-27 16:31 UTC, wrgraff commented on source/sass/blocks/order-form.scss
> +    height: 4px;
Так элементы то 2 пикселя высотой по макету )

2023-04-27 16:31 UTC, wrgraff commented on source/sass/blocks/hero.scss
> +    width: 100vw;
Горизонтальная прокрутка создалась, надо от нее избавиться

2023-04-27 16:31 UTC, wrgraff commented on source/sass/blocks/form-group.scss
> +      // grid-row: 2;
Нужно чтобы не было закомментированного кода в нашем мастер-репозитории, формально это ошибка будет

2023-04-27 18:15 UTC, dornp commented on source/sass/blocks/hero.scss
> +    width: 100vw;
Странно, ни в одном браузере у меня нет горизонтальной прокрутки... Сделала `overflow: hidden`; на `.page__main` на всякий случай.

2023-04-27 18:56 UTC, wrgraff approved these changes

2023-04-27 18:56 UTC, merged

2023-04-27 19:04 UTC, wrgraff commented on source/sass/blocks/hero.scss
> +    width: 100vw;
На мобильной щирине она есть, но без тач-режима, потому что она из-за скроллбара появляется