Оптимизация графики
htmlacademy-adaptive/2280491-cat-energy-28 pull request #7
Opened 2023-05-03 14:59 UTC by dornp

2023-05-03 15:00 UTC, dornp commented
Посмотри, пожалуйста, правильно ли я сделала состояния для ползунка в слайдере.

2023-05-03 17:29 UTC, wrgraff requested changes

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +
У наших нарисованных чекбоксов нет по умолчанию состояния `:focus`, поэтому нам его надо придумать.
Фокус — это такая обводка, как ты знаешь. Она довольно контрастная. Воспроизвести браузерную мы не сможем чисто технически, поэтому можно тоже сделать что-то контрастное

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  }
А почему и повторяющиеся свойства фона не включить в основной псевдоэлемент?
```scss
  &::after {
    content: "";
    position: absolute;
    width: 20px;
    height: 20px;
    top: 13px;
    right: 15px;
    background-color: v.$black-color;
    background-repeat: no-repeat;
  }

  &--owner-mail::after {
    mask: url("../img/sprite.svg#mail");
  }

  &--owner-phone::after {
    mask: url("../img/sprite.svg#phone");
  }
```

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +    border: none;
Рамка включена в размер инпутов, поэтому когда ты ее обнуляешь, инпут становится чуть меньше. И получается небольшое "подергивание" элементов.

Лучше не меняй рамку, а пускай ее просто перекроет `outline`.
`outline`, кстати, в этих инпутах направлен должен быть внутрь (по умолчанию он от границ наружу). Посмотри свойство `outline-offset`.

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  &:focus:invalid {
Делая это состояние для фокуса ты решаешь проблему того, что изначально все поля подсвечены красным.
Но так они становятся подсвечены красным сразу же при фокусе, что тоже не очень хорошо.
Вместо этой конструкции используй `&:user-invalid`, это свойство добавляет рамку только тем полям, с которыми пользователь повзаимодействовал.
У него раньше была не очень хорошая поддержка, но на данный момент она уже достаточно широкая

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  &::-webkit-inner-spin-button {
Если что, в файрфоксе эти спин-кнопочки еще остались (хотя, я бы их и вовсе не убирал, если они явно не мешают в поле)

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/logo.scss
> +  &:focus {
Не нужно объединять наведение и фокус. Фокус — это рамка, если на элемент в фокусе навести курсор, то к нему прибавятся стили наведения (и рамка останется). Это 2 состояния, они работаю независимо, поэтому не стоит их объединять

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/program.scss
> +    mask: url("../img/sprite.svg#arrow-short-program");
Не очень понятно зачем делать через маску, если можно сделать фоновой картинкой?

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/program.scss
> +      mask: url("../img/sprite.svg#arrow-long-program");
А еще можно обойтись и одной длинной картинкой. Сделать короткую стрелку можно просто сместив при наведении положение фона внутри псевдоэлемента влево

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/radio.scss
> +.radio__text:hover::before {
Для радио-кнопок тоже хорошо бы придумать фокусное состояние.

Точнее, не хорошо бы, у нас там критерий про это есть, поэтому вообще-то надо придумать ))

2023-05-03 17:29 UTC, wrgraff commented on source/sass/blocks/slider.scss
> +  .slider__button {
Кнопка все-таки должна реагировать на взаимодействие именно тогда, когда мы наводим на кнопку, а не на весь слайдер. При этом, вертикальная полоса в такой концепции — тоже часть кнопки.
Получается такая странненькая кнопка, но вот как уж нарисовали

2023-05-03 17:30 UTC, wrgraff commented
Не очень много правок, и больше по состояниям, чем по оптимизации.
С оптимизацией все ок =)

2023-05-04 10:06 UTC, dornp commented on source/sass/blocks/form-field.scss
> +  }
Тогда у меня окрасятся поля выше. Класс элемента `.form-field__label`, к которому привязан псевдоэлемент - общий для всех инпутов. Видимо, придётся переписать классы у лэйблов.

2023-05-04 10:07 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  }
Хм. Как это поля окрасятся? Это же псевдоэлемент

2023-05-04 10:10 UTC, dornp commented on source/sass/blocks/form-field.scss
> +  }
У меня получается, что создаётся псевдоэлемент не толко у лэйблов с информацией про контактные данные владельца, но и у лэйблов с информацией о коте. Так, эти псевдоэлементы были прозрачными, а с background-color появились чёрные квадратики 20 на 20 у полей имя, вес, возраст

2023-05-04 10:11 UTC, dornp commented on source/sass/blocks/form-field.scss
> +  }
Тут надо классы у лэйблов разные делать у этих блоков

2023-05-04 10:14 UTC, dornp commented on source/sass/blocks/form-field.scss
> +  }
Я исправила все

2023-05-04 10:17 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  }
Мммм... Тогда надо бы избежать создания псевдоэлементов у всех подряд.
Я это пропустил, но вообще это не очень то хорошо, что создаются лишние участники DOM-дерева.

Можно тогда усложнить и например задать псевдоэлемент тем лейблам, что имеют класс, в котором есть модификатор, содержащий иконку: `&[class*="--owner"]::after`.

Мне тут не очень нравится еще название `owner`. Нам то по идее важно, что это инпут с иконкой, а что это инпуты про контактные данные владельца кота, нам для оформления не важно. Мы тут завязываемся на смысл, а надо на оформление.
Мало ли где еще на сайте инпут с иконкой придумают.

Можно так и писать: `&--icon-mail`. Максимально абстрактно, но и понятно. Можно даже представить модификатор как пару "ключ: значение".

2023-05-04 11:02 UTC, dornp commented on source/sass/blocks/form-field.scss
> +  }
А нельзя просто классы у лэйблов разные сделать? К примеру, у блока с информацией о коте `form-field__label`, а контактных данных владельца `form-field__label-contacts`?

2023-05-04 11:25 UTC, dornp commented on source/sass/blocks/form-field.scss
> +  &:focus:invalid {
Chrome не поддерживает `&:user-invalid`

2023-05-04 11:49 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  }
Ну как-то не очень, потому что в чем разница между ними? У одних иконка есть, а у других нет. Это модификация скорее.

Можно тогда чтобы сделать проще именно селекторы добавить 2 модификатора. Один будет добавлять псевдик под иконку, а другой — указывать какую иконку.

2023-05-04 11:54 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  &:focus:invalid {
Я бы все равно внедрял уже новое свойство.

Но в любом случае, не подходит вариант, при котором любое пустое поле в фокусе становится красным: так быть не должно. Тем более, что после взаимодействия оно должно остаться красным даже при снятом фокусе.

Можно сделать по старинке: подготовить модификатор, который будет добавлять красную рамку.
А модификаторы такие расставляет JS, там можно очень хорошо контролировать валидацию

2023-05-04 14:05 UTC, dornp commented on source/sass/blocks/program.scss
> +      mask: url("../img/sprite.svg#arrow-long-program");
Можно я так оставлю? Я так понимаю, что это не критично)

2023-05-04 16:27 UTC, wrgraff approved these changes
Отлично =)

2023-05-04 16:27 UTC, wrgraff commented on source/form.html
> +                  <input class="visually-hidden radio__input" type="radio" name="program" value="weight-loss" checked>
Не спеши скрывать чекбоксы через `visually-hidden`. Это не самый оптимальный и лучший способ скрытия для доступности. У Сары Суайдан есть [целая статья про способы прятать чекбоксы доступно](https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/), и там это подробно разобрано.

Статья большая и на английском, поэтому, если тебе не хочется / некогда / сложно ее читать, вот основная идея:

> Есть для незрячих такой способ взаимодействия с интерфейсом: водить пальцем по экрану и слушать что под ним. При таком сценарии пользователь около лейбла будет ожидать увидеть чекбокс. Так что гораздо лучше, если он не будет скрыт, а будет там реально находиться.
> 
> Как это сделать:
> 1. убрать чекбокс из потока с помощью, `position: absolute`;
> 2. расположить его поверх изображения, которое визуально изображает чекбокс;
> 3. установить его размеры, чтобы они соответствовали размеру изображения;
> 4. визуально скрыть чекбокс с помощью ****`opacity: 0`.
> 
> https://user-images.githubusercontent.com/37917037/128550004-fb60ed66-cd1c-4bd4-8d31-2771be5d09b0.mp4

2023-05-04 16:27 UTC, wrgraff commented on source/sass/blocks/logo.scss
> +    }
Все равно непонятно зачем мы меняем прозрачность при фокусировке, чем переписываем стили при наведении. На наведение логотип в футере уже не среагирует, ведь это правило переписывает ховер...

2023-05-04 16:27 UTC, merged

2023-05-05 19:28 UTC, wrgraff commented on source/sass/blocks/program.scss
> +      mask: url("../img/sprite.svg#arrow-long-program");
Ну, оставить то можно, но это не оптимально. Мы могли бы сделать спрайт поменьше или можно подумать о реализации без псевдоэлемента (но там с переполнением нужно аккуратнее быть, может быть не очень красиво).

Есть еще случаи, когда картинка не в спрайте. Тогда при изменении состояния она может "моргнуть", так как будет загружаться только в этот момент. Картинка маленькая, загрузится быстро, но глаз заметит. Тут это не актуально, но стоит иметь ввиду