Улучшение скорости загрузки
htmlacademy-adaptive/2280491-cat-energy-28 pull request #9
Opened 2023-05-15 10:43 UTC by dornp

2023-05-15 18:59 UTC, wrgraff requested changes
Раз у нас оптимизация загрузки шрифтов (хоть мы и используем для pixel perfect и шлифовки этот этап), то надо все-таки [прелоады](https://up.htmlacademy.ru/adaptive/28/criteries#d23) добавить =)

На странице формы потерялся один из классов в футере:
<img width="445" alt="изображение" src="https://github.com/htmlacademy-adaptive/2280491-cat-energy-28/assets/37917037/05269ce3-f899-41f4-9792-e257b3b364fb">

Есть ошибки по [валидатору](https://validator.w3.org/nu/#textarea), нужно их обязательно поправить.

---

Что-то мудреное творится, видимо в первую очередь с переполнением. Нет ли тут повода для консультации, чтобы разобраться что к чему?

2023-05-15 18:59 UTC, wrgraff commented on source/form.html
> +                img/map/map-tablet@2x.jpg 1x" width="768" height="400">
Видимо опечатка, идет 1x оба раза

2023-05-15 18:59 UTC, wrgraff commented on source/catalog.html
> +        <div class="page-header__logo-btn">
А стили под работу с js пока отсутствуют?

2023-05-15 18:59 UTC, wrgraff commented on source/index.html
> +          title="Офис компании по адресу ул. Большая Конюшенная, д. 19/8 Санкт-Петербург"
А зачем ему `title`?

2023-05-15 18:59 UTC, wrgraff commented on source/sass/blocks/checkbox.scss
> +  word-break: break-all;
Нет-нет, такой перенос делать нельзя, так же текст будет нечитаемый:
<img width="306" alt="изображение" src="https://github.com/htmlacademy-adaptive/2280491-cat-energy-28/assets/37917037/060a4a3a-2a59-4b78-a36c-d37b15b59492">

Зачем так?

2023-05-15 18:59 UTC, wrgraff commented on source/sass/blocks/extra-product-card.scss
> +  word-wrap: break-word;
Вообще-то, должно быть `word-break`.
Но зачем оно здесь?

2023-05-15 18:59 UTC, wrgraff commented on source/sass/blocks/extra-product-card.scss
> +  word-break: break-all;
`break-all` вообще нельзя использовать для текста

2023-05-15 18:59 UTC, wrgraff commented on source/sass/blocks/form-field.scss
> +  }
А если у нас будет меняться текст в подписях?
Нет, так не пойдет. Тем более, для флекса можно эту задачу решить лучше. Например, поставить небольшую ширину инпуту, чтобы он не сжимался в ноль. а затем настроить так, чтобы он все свободное пространство забирал себе

2023-05-15 18:59 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +}
Что это и зачем оно здесь?
Ломается же сетка:
<img width="647" alt="изображение" src="https://github.com/htmlacademy-adaptive/2280491-cat-energy-28/assets/37917037/f6235001-0b9c-4c00-8b5f-8a538b51bf8a">

А потом элементы списка получают ширину 100vw, чтобы выпадать из этого ограничения.
И при определенных условиях 100vw создает горизонтальную прокрутку.

Что эти стили делают, не пойму — отключил и ничего не поменялось

2023-05-15 18:59 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +    max-width: 443px;
Из чего такое ограничение появилось?

Вообще, очень много `max-width` по всему проекту пошло, но не везде они оправданы

2023-05-15 18:59 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +  min-width: 280px;
Минимальную ширину в 320 точек надо поставить на весь сайт полностью, это его минимально возможная рабочая ширина (берется из макета, мобильная версия отрисована на минимально возможной ширине).
Чтобы сайт не перекашивало, именно для него в целом нужно указать ширину, например на `body`.

И по элементам тогда минимальную ширину не надо будет ставить (хотя и так не понимаю зачем она)

2023-05-16 09:26 UTC, dornp commented on source/index.html
> +          title="Офис компании по адресу ул. Большая Конюшенная, д. 19/8 Санкт-Петербург"
Lighthouse требует title для iframe для улучшения perfomance

2023-05-16 10:19 UTC, dornp commented on source/sass/blocks/main-nav.scss
> +}
Убрала на мобильной версии, но если убрать max-width на планшете или десктопе, получается так 
<img width="600" alt="Снимок экрана 2023-05-16 в 13 03 29" src="https://github.com/htmlacademy-adaptive/2280491-cat-energy-28/assets/104000652/440e0e5c-e9fd-4985-976e-ed4ed1ec9aa0">

2023-05-16 10:24 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +}
А что это такое? Текст одной ссылки?
Всё-таки, когда тестируется сайт на переполнение, надо иметь ввиду реалистичные сценарии. Ссылка в главном меню из 6 слов — такого не бывает даже в высоко нагруженных интерфейсах.

Но поведение да, несколько странное. И тут я бы смотрел в первую очередь почему сетка ломается и как сделать ее устойчивее в целом

2023-05-16 10:44 UTC, dornp commented on source/sass/blocks/main-nav.scss
> +}
Если добавлять ещё пункты меню без max-width тоже съезжает. Мне кажется, здесь нужен max-width
<img width="842" alt="Снимок экрана 2023-05-16 в 13 42 39" src="https://github.com/htmlacademy-adaptive/2280491-cat-energy-28/assets/104000652/1006f12e-0fcd-49e6-9e19-c1fe957f00e9">

2023-05-16 10:47 UTC, wrgraff commented on source/sass/blocks/main-nav.scss
> +}
Из того, что я вижу — проблема в ломающейся сетке.
max-width — это костыль, а не решение изначальной проблемы

2023-05-16 16:59 UTC, wrgraff approved these changes

2023-05-16 16:59 UTC, merged